version: "3.9"
services:
  mongodb-tf:
    image: mongo:6.0.2
    container_name: mongodb_truyenful
    environment:
      MONGO_INITDB_ROOT_USERNAME: truyenful
      MONGO_INITDB_ROOT_PASSWORD: nuAfBHEH3bbC8MH
    volumes:
      - mongo_db:/data/db
    ports:
      - 8465:27017
    networks:
      - tf-be-network
    restart: always
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--accesslog.filePath=/docker/logs/traefik-access.log"
      - "--log.filePath=/docker/logs/traefik-log.log"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/:/logs/
    networks:
      - be_network
  category-service:
    container_name: category-service
    env_file:
      - .env
    build:
      context: category-service
      dockerfile: Dockerfile
      target: development
    labels:
      - traefik.enable=true
      - "traefik.http.routers.category-service.rule=((PathPrefix(`/api/v1/public/category`) || PathPrefix(`/api/v1/admin/category`)) || || PathPrefix(`/api/v1/user/category`))"
      - traefik.http.services.category-service.loadbalancer.server.port=8888
    networks:
      - be_network
    depends_on:
      - mongodb-tf
  list-type-service:
    container_name: list-type-service
    env_file:
      - .env
    build:
      context: list-type-service
      dockerfile: Dockerfile
      target: development
    labels:
      - traefik.enable=true
      - "traefik.http.routers.category-service.rule=((PathPrefix(`/api/v1/public/list-types`) || PathPrefix(`/api/v1/admin/list-types`)) || || PathPrefix(`/api/v1/user/list-types`))"
      - traefik.http.services.list-type-service.loadbalancer.server.port=8889
    networks:
      - be_network
    depends_on:
      - mongodb-tf
networks:
  be_network:
    driver: bridge
