version: "3.9"
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command: 
    - "--api.insecure=true"
    - "--providers.docker"
    - "--accesslog.filePath=/logs/access.log"
    - "--log.filePath=/logs/log.log"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/:/logs/
    networks:
      - be_network
  category-service:
    container_name: category-service
    env_file:
      - .env
    build:
      context: category-service
      dockerfile: Dockerfile
      target: development
    ports:
      - 8887:8887
    labels:
      - traefik.enable=true
      - "traefik.http.routers.category-service.rule=PathPrefix(`/auth`)"
      - traefik.http.services.category-service.loadbalancer.server.port=8888
    networks:
      - be_network
  list-type-service:
    container_name: list-type-service
    env_file:
      - .env
    build:
      context: list-type-service
      dockerfile: Dockerfile
      target: development
    labels:
      - traefik.enable=true
      - "traefik.http.routers.list-type-service.rule=PathPrefix(`/chat`)"
      - traefik.http.services.list-type-service.loadbalancer.server.port=8889
    networks:
      - be_network
networks:
  be_network:
    driver: bridge
